module.exports = [
  { username: 'Aharon', text: 'hey there', room: 'Aharon' },
  { username: 'Aharon', text: 'hey there', room: 'lobby' },
  { username: 'Clair', text: 'some thing fun', room: 'lobby' },
  { username: 'Clair', text: 'whooppsy', room: 'lobby' },
  { username: 'Clair', text: 'more word', room: 'lobby' },
  { username: 'Aharon', text: 'im here', room: 'lobby' },
  { username: 'Aharon', text: 'Having technical difficulties', room: 'lobby' },
  { username: 'Aharon', text: 'helped me out', room: 'lobby' },
  {
    username: 'Aharon',
    text: 'Using the term throwback regarding the 90’s makes me feel old',
    room: 'Aharon',
  },
  { username: 'Clair', text: 'workshop later', room: 'Aharon' },
  {
    username: 'Clair',
    text: 'anyone thinking of using redis',
    room: 'Aharon',
  },
  { username: 'Aharon', text: 'fun fun', room: 'Aharon' },
  { username: 'Dan', text: 'will it mount', room: 'React-ion' },
  { username: 'Aharon', text: 'what is a hook', room: 'React-ion' },
  { username: 'Dan', text: 'do you class', room: 'React-ion' },
  { username: 'Aharon', text: 'should i learn angular', room: 'React-ion' },
  { username: 'Aharon', text: 'why is it not rendering', room: 'React-ion' },
  { username: 'Clair', text: 'why wont it stop rendering', room: 'React-ion' },
  { username: 'Clair', text: 'should i use redux', room: 'React-ion' },
  { username: 'Dan', text: 'but why not Jquery', room: 'React-ion' },
  { username: 'Dan', text: 'help', room: 'React-ion' },
  { username: 'Dan', text: 'yes it really does', room: 'React-ion' },
  { username: 'Aharon', text: 'nah its good', room: 'RedSucks' },
  { username: 'Aharon', text: "you'll get used to it", room: 'RedSucks' },
  { username: 'Dan', text: 'will I?', room: 'RedSucks' },
  { username: 'Clair', text: 'No', room: 'RedSucks' },
];
